### ISSUE TITLE
Using curl getting an error Inavalid grant

### ISSUE THREAD

**Issue by ravitej91** [widop/WidopHttpAdapterBundle#15]
I have configured my aplication with Widop google Analytics Bundle 1.0.0 and Widop Http Adapter Bundle 1.0.0
and when I try to access my application I got the Error
"Failed to retrieve access token(Invalid Grant)"
I've tried with buzz . It gives me an different error
"Failed to open stream"
What is the exact error?

**Comment by geoffrey-brier** [comment]
Hi!
Concerning buzz, by default it does not support `https` queries as the browser uses the `FileGetContents` client.
Now concerning the problem you have with analytics I recommend to carefully read the docs ([here](https://github.com/widop/google-analytics/blob/master/doc/usage.md#get-your-credentials) and [here](https://github.com/widop/WidopGoogleAnalyticsBundle/blob/master/Resources/doc/usage.md)) as you might have missed something.

**Comment by egeloen** [comment]
@ravitej91 AFAIR the 1.0.0 version is buggy. Can you update to the latest 1.0.\* version? Or event better update to a 1.1.\* release.

**Comment by ravitej91** [comment]
Yep thanks the issue was solved
